### ISSUE TITLE
Minfree is set really high by default, and isn't devined in init.lena.rc

### ISSUE THREAD

**Issue by JacekJagosz** [sonyxperiadev/device-sony-lena#16]
Users of SailfishOS noticed that even with 6GB of RAM apps are killed quicker than expected. [The issue has been traced to `/sys/module/lowmemorykiller/parameters/minfree` being set much higher than on any previous device](https://forum.sailfishos.org/t/tuning-the-oom-killer-low-memory-killer/12676/).
```bash
cat /sys/module/lowmemorykiller/parameters/minfree
167160,190200,213240,236280,356490
```
Meanwhile Seine, Ganges and Nile all used: `15360,19200,23040,26880,34415,43737`
I also noticed that [previous Sony devices had `minfree` values defined in `init.rc`](https://github.com/sonyxperiadev/device-sony-seine/blob/4bb811d6271e913b356216a6423b296aedec77bf/rootdir/vendor/etc/init/init.seine.rc#L61), meanwhile Lena lacks it. Could it possibly be an omission, that causes the system to use Android defaults?
Also could the values be lowered, closer to the values used on previous devices? On SailfishOS we tested values cut by half, and they improved responsibility, while still being higher than on older devices.

**Comment by JacekJagosz** [comment]
Is `LMK` (lowmemorykiller) still used in Android 11 and 12? Only reason I see why this configuration got omitted compared to previous devices is that in-kernel `LMK` is no longer used in Android in favour of user-space `LMKD` ([Low Memory Killer Daemon](https://source.android.com/devices/tech/perf/lmkd)).
But even if that is the case, now the `LMKD` is not configured and will be left using default values, as it took values from `LMK`. So Android users are still loosing out, while SFOS users are very much affected, as that OS still utilizes `LMK`.

**Comment by jerpelea** [comment]
we can use the LMK config even if it is not used by Android so that everybody is covered

**Comment by JacekJagosz** [comment]
I did more research and [Sailfish OS is patching those lines back in already](https://github.com/mer-hybris/droid-src-sony/blob/5f8c2e0c58efbae2bea3e793d9ae10dbe336ccf6/patches/device/sony/lena/0001-hybris-init-Enable-low-memory-killer.patch), although with much higher values than Sony used on all the previous devices. So I will bring the discussion to them why they chose values so high.
But the question still remains why is Sony no longer doing it, won't it lead to devices using default values for both `LMK` and `LMKD`?

**Comment by jerpelea** [comment]
feel free to send the patch upstream
